#!/bin/bash

gh api --method POST repos/riseproject-dev/pytorch-ci/dispatches --input - <<EOF
{
  "event_type": "push",
  "client_payload": {
    "delivery_id": "096c0320-43e5-11f1-8fcf-4d64e257ae36",
    "event_type": "push",
    "payload": {
      "after": "5125a13e379d9dd74867cc820cd3d73b92a575e0",
      "base_ref": "refs/heads/main",
      "before": "0000000000000000000000000000000000000000",
      "commits": [],
      "compare": "https://github.com/pytorch/pytorch/compare/trunk/5125a13e379d9dd74867cc820cd3d73b92a575e0",
      "created": true,
      "deleted": false,
      "enterprise": {
        "avatar_url": "https://avatars.githubusercontent.com/b/1642?v=4",
        "created_at": "2019-12-12T00:17:22Z",
        "description": "",
        "html_url": "https://github.com/enterprises/meta",
        "id": 1642,
        "name": "Meta Platforms, Inc.",
        "node_id": "MDEwOkVudGVycHJpc2UxNjQy",
        "slug": "meta",
        "updated_at": "2026-02-06T20:43:24Z",
        "website_url": "https://meta.com"
      },
      "forced": false,
      "head_commit": {
        "added": [],
        "author": {
          "date": "2026-04-29T16:02:10Z",
          "email": "desmaison.alban@gmail.com",
          "name": "albanD",
          "username": "albanD"
        },
        "committer": {
          "date": "2026-04-29T16:02:10Z",
          "email": "pytorchmergebot@users.noreply.github.com",
          "name": "PyTorch MergeBot",
          "username": "pytorchmergebot"
        },
        "distinct": true,
        "id": "5125a13e379d9dd74867cc820cd3d73b92a575e0",
        "message": "[lint] Register RAWTHROW linter and make unknown-linter check a hard error (#181879)\n\n## Author Notes\nFixes the \"spin lint\" unknown lint to be a proper error. Otherwise, new lint will be silently not run in CI.\nEmergency cleanup of rawthrow skip list. Will burn it down next.\n\n## Agent Notes\n\nThe RAWTHROW linter was added to  but never registered in , causing CI to fail with \"Unknown linters found\" while  passed locally (because the check was only a warning).\n\nTwo fixes:\n1. Register  in  and expand the exclude list with 31 directory-level glob patterns covering all 1433 pre-existing violations (334 files), so the linter is clean and new code outside those directories is enforced immediately.\n2. Upgrade the unknown/missing linter validation in  from a yellow warning to a hard error, so this class of issue is caught by  locally going forward.\n\nAuthored with Claude.\n\n## Test plan\n\n- Verified  passes locally\n- Verified  produces zero violations\n- Verified  now hard-fails when a linter is missing from \nPull Request resolved: https://github.com/pytorch/pytorch/pull/181879\nApproved by: https://github.com/ezyang, https://github.com/Skylion007",
        "modified": [
          ".lintrunner.toml",
          ".spin/cmds.py"
        ],
        "removed": [],
        "timestamp": "2026-04-29T16:02:10Z",
        "tree_id": "532310b3bd64ed3850127a600545d1fe7d4435b4",
        "url": "https://github.com/pytorch/pytorch/commit/5125a13e379d9dd74867cc820cd3d73b92a575e0"
      },
      "installation": {
        "id": 122659619,
        "node_id": "MDIzOkludGVncmF0aW9uSW5zdGFsbGF0aW9uMTIyNjU5NjE5"
      },
      "organization": {
        "avatar_url": "https://avatars.githubusercontent.com/u/21003710?v=4",
        "description": "",
        "events_url": "https://api.github.com/orgs/pytorch/events",
        "hooks_url": "https://api.github.com/orgs/pytorch/hooks",
        "id": 21003710,
        "issues_url": "https://api.github.com/orgs/pytorch/issues",
        "login": "pytorch",
        "members_url": "https://api.github.com/orgs/pytorch/members{/member}",
        "node_id": "MDEyOk9yZ2FuaXphdGlvbjIxMDAzNzEw",
        "public_members_url": "https://api.github.com/orgs/pytorch/public_members{/member}",
        "repos_url": "https://api.github.com/orgs/pytorch/repos",
        "url": "https://api.github.com/orgs/pytorch"
      },
      "pusher": {
        "email": null,
        "name": "github-actions[bot]"
      },
      "ref": "refs/tags/trunk/5125a13e379d9dd74867cc820cd3d73b92a575e0",
      "repository": {
        "allow_forking": true,
        "archive_url": "https://api.github.com/repos/pytorch/pytorch/{archive_format}{/ref}",
        "archived": false,
        "assignees_url": "https://api.github.com/repos/pytorch/pytorch/assignees{/user}",
        "blobs_url": "https://api.github.com/repos/pytorch/pytorch/git/blobs{/sha}",
        "branches_url": "https://api.github.com/repos/pytorch/pytorch/branches{/branch}",
        "clone_url": "https://github.com/pytorch/pytorch.git",
        "collaborators_url": "https://api.github.com/repos/pytorch/pytorch/collaborators{/collaborator}",
        "comments_url": "https://api.github.com/repos/pytorch/pytorch/comments{/number}",
        "commits_url": "https://api.github.com/repos/pytorch/pytorch/commits{/sha}",
        "compare_url": "https://api.github.com/repos/pytorch/pytorch/compare/{base}...{head}",
        "contents_url": "https://api.github.com/repos/pytorch/pytorch/contents/{+path}",
        "contributors_url": "https://api.github.com/repos/pytorch/pytorch/contributors",
        "created_at": 1471066001,
        "custom_properties": {},
        "default_branch": "main",
        "deployments_url": "https://api.github.com/repos/pytorch/pytorch/deployments",
        "description": "Tensors and Dynamic neural networks in Python with strong GPU acceleration",
        "disabled": false,
        "downloads_url": "https://api.github.com/repos/pytorch/pytorch/downloads",
        "events_url": "https://api.github.com/repos/pytorch/pytorch/events",
        "fork": false,
        "forks": 27619,
        "forks_count": 27619,
        "forks_url": "https://api.github.com/repos/pytorch/pytorch/forks",
        "full_name": "pytorch/pytorch",
        "git_commits_url": "https://api.github.com/repos/pytorch/pytorch/git/commits{/sha}",
        "git_refs_url": "https://api.github.com/repos/pytorch/pytorch/git/refs{/sha}",
        "git_tags_url": "https://api.github.com/repos/pytorch/pytorch/git/tags{/sha}",
        "git_url": "git://github.com/pytorch/pytorch.git",
        "has_discussions": false,
        "has_downloads": true,
        "has_issues": true,
        "has_pages": false,
        "has_projects": true,
        "has_pull_requests": true,
        "has_wiki": true,
        "homepage": "https://pytorch.org",
        "hooks_url": "https://api.github.com/repos/pytorch/pytorch/hooks",
        "html_url": "https://github.com/pytorch/pytorch",
        "id": 65600975,
        "is_template": false,
        "issue_comment_url": "https://api.github.com/repos/pytorch/pytorch/issues/comments{/number}",
        "issue_events_url": "https://api.github.com/repos/pytorch/pytorch/issues/events{/number}",
        "issues_url": "https://api.github.com/repos/pytorch/pytorch/issues{/number}",
        "keys_url": "https://api.github.com/repos/pytorch/pytorch/keys{/key_id}",
        "labels_url": "https://api.github.com/repos/pytorch/pytorch/labels{/name}",
        "language": "Python",
        "languages_url": "https://api.github.com/repos/pytorch/pytorch/languages",
        "license": {
          "key": "other",
          "name": "Other",
          "node_id": "MDc6TGljZW5zZTA=",
          "spdx_id": "NOASSERTION",
          "url": null
        },
        "master_branch": "main",
        "merges_url": "https://api.github.com/repos/pytorch/pytorch/merges",
        "milestones_url": "https://api.github.com/repos/pytorch/pytorch/milestones{/number}",
        "mirror_url": null,
        "name": "pytorch",
        "node_id": "MDEwOlJlcG9zaXRvcnk2NTYwMDk3NQ==",
        "notifications_url": "https://api.github.com/repos/pytorch/pytorch/notifications{?since,all,participating}",
        "open_issues": 18538,
        "open_issues_count": 18538,
        "organization": "pytorch",
        "owner": {
          "avatar_url": "https://avatars.githubusercontent.com/u/21003710?v=4",
          "email": null,
          "events_url": "https://api.github.com/users/pytorch/events{/privacy}",
          "followers_url": "https://api.github.com/users/pytorch/followers",
          "following_url": "https://api.github.com/users/pytorch/following{/other_user}",
          "gists_url": "https://api.github.com/users/pytorch/gists{/gist_id}",
          "gravatar_id": "",
          "html_url": "https://github.com/pytorch",
          "id": 21003710,
          "login": "pytorch",
          "name": "pytorch",
          "node_id": "MDEyOk9yZ2FuaXphdGlvbjIxMDAzNzEw",
          "organizations_url": "https://api.github.com/users/pytorch/orgs",
          "received_events_url": "https://api.github.com/users/pytorch/received_events",
          "repos_url": "https://api.github.com/users/pytorch/repos",
          "site_admin": false,
          "starred_url": "https://api.github.com/users/pytorch/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/pytorch/subscriptions",
          "type": "Organization",
          "url": "https://api.github.com/users/pytorch",
          "user_view_type": "public"
        },
        "private": false,
        "pull_request_creation_policy": "all",
        "pulls_url": "https://api.github.com/repos/pytorch/pytorch/pulls{/number}",
        "pushed_at": 1777478640,
        "releases_url": "https://api.github.com/repos/pytorch/pytorch/releases{/id}",
        "size": 1312353,
        "ssh_url": "org-21003710@github.com:pytorch/pytorch.git",
        "stargazers": 99527,
        "stargazers_count": 99527,
        "stargazers_url": "https://api.github.com/repos/pytorch/pytorch/stargazers",
        "statuses_url": "https://api.github.com/repos/pytorch/pytorch/statuses/{sha}",
        "subscribers_url": "https://api.github.com/repos/pytorch/pytorch/subscribers",
        "subscription_url": "https://api.github.com/repos/pytorch/pytorch/subscription",
        "svn_url": "https://github.com/pytorch/pytorch",
        "tags_url": "https://api.github.com/repos/pytorch/pytorch/tags",
        "teams_url": "https://api.github.com/repos/pytorch/pytorch/teams",
        "topics": [
          "autograd",
          "deep-learning",
          "gpu",
          "machine-learning",
          "neural-network",
          "numpy",
          "python",
          "tensor"
        ],
        "trees_url": "https://api.github.com/repos/pytorch/pytorch/git/trees{/sha}",
        "updated_at": "2026-04-29T16:02:23Z",
        "url": "https://api.github.com/repos/pytorch/pytorch",
        "visibility": "public",
        "watchers": 99527,
        "watchers_count": 99527,
        "web_commit_signoff_required": false
      },
      "sender": {
        "avatar_url": "https://avatars.githubusercontent.com/in/15368?v=4",
        "events_url": "https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}",
        "followers_url": "https://api.github.com/users/github-actions%5Bbot%5D/followers",
        "following_url": "https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}",
        "gists_url": "https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/apps/github-actions",
        "id": 41898282,
        "login": "github-actions[bot]",
        "node_id": "MDM6Qm90NDE4OTgyODI=",
        "organizations_url": "https://api.github.com/users/github-actions%5Bbot%5D/orgs",
        "received_events_url": "https://api.github.com/users/github-actions%5Bbot%5D/received_events",
        "repos_url": "https://api.github.com/users/github-actions%5Bbot%5D/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/github-actions%5Bbot%5D/subscriptions",
        "type": "Bot",
        "url": "https://api.github.com/users/github-actions%5Bbot%5D",
        "user_view_type": "public"
      }
    }
  }
}
EOF