#!/bin/bash

gh api --method POST repos/riseproject-dev/pytorch-ci/dispatches --input - <<EOF
{
  "event_type": "push",
  "client_payload": {
    "delivery_id": "b96a7624-43e7-11f1-9cd5-19350f850bb0",
    "event_type": "push",
    "payload": {
      "after": "cb0d97e95f00e31f4de9fb617e19ee785da49b4b",
      "base_ref": "refs/heads/gh/aorenste/280/head",
      "before": "0000000000000000000000000000000000000000",
      "commits": [],
      "compare": "https://github.com/pytorch/pytorch/compare/ciflow/riscv64/181785",
      "created": true,
      "deleted": false,
      "enterprise": {
        "avatar_url": "https://avatars.githubusercontent.com/b/1642?v=4",
        "created_at": "2019-12-12T00:17:22Z",
        "description": "",
        "html_url": "https://github.com/enterprises/meta",
        "id": 1642,
        "name": "Meta Platforms, Inc.",
        "node_id": "MDEwOkVudGVycHJpc2UxNjQy",
        "slug": "meta",
        "updated_at": "2026-02-06T20:43:24Z",
        "website_url": "https://meta.com"
      },
      "forced": false,
      "head_commit": {
        "added": [
          ".claude/skills/distributed-triage/SKILL.md",
          ".claude/skills/distributed-triage/distributed-labels.json",
          ".claude/skills/distributed-triage/distributed-rubric.md",
          ".claude/skills/distributed-triage/templates.json",
          ".github/workflows/claude-distributed-triage-cron.yml",
          ".github/workflows/claude-distributed-triage.yml",
          "aten/src/ATen/native/mps/kernels/PrefillAttention.h",
          "c10/core/StorageMaterializer.h",
          "cmake/FileMirroring.cmake",
          "test/dynamo/test_id.py",
          "torch/csrc/inductor/aoti_runtime/cpu_triton_runtime_wrappers.h"
        ],
        "author": {
          "date": "2026-04-29T09:22:57-07:00",
          "email": "aorenste@fb.com",
          "name": "Aaron Orenstein",
          "username": "aorenste"
        },
        "committer": {
          "date": "2026-04-29T09:22:57-07:00",
          "email": "aorenste@fb.com",
          "name": "Aaron Orenstein",
          "username": "aorenste"
        },
        "distinct": true,
        "id": "cb0d97e95f00e31f4de9fb617e19ee785da49b4b",
        "message": "Update on \"Fix Library finalizer not clearing torch.ops cache\"\n\n\nCalling  on a  ran the weakref finalizer but\nleft the cached  on  in place. The\nC++ side had been reset, but  still listed\n'default' while  now raised . Any\nlater code that walked all CompositeImplicitAutograd ops would hit that --\nmost visibly,  at\n, where CPython's  opcode\nrewrote the  as the misleading\n.\n\n already did this cleanup, so the explicit-teardown path\n(e.g. ) was fine; only the gc-driven finalizer path was\nbroken. Extracted the cleanup into  and called it\nfrom  as well.\n\nThis was hitting slow-gradcheck periodic in test_torch.py:\n creates a DEF-mode\nLibrary, calls its op, then lets it go out of scope; subsequent CUDA tests\nthen crashed in  ->  ->\nthe lazy import chain above.\n\nFixes #181765. The flaky-test disabler had been auto-creating per-test\nissues (#181343, #181537, #181684, #119515) papering over this -- those\ntests should be re-enabled once this lands.\n\nAuthored with Claude.\n\n[ghstack-poisoned]",
        "modified": [
          ".ci/magma-rocm/Makefile",
          ".claude/skills/triaging-issues/SKILL.md",
          ".claude/skills/triaging-issues/scripts/validate_labels.py",
          ".github/merge_rules.yaml",
          ".github/workflows/build-magma-rocm-linux.yml",
          ".github/workflows/claude-issue-triage-run.yml",
          ".lintrunner.toml",
          ".spin/cmds.py",
          "CMakeLists.txt",
          "aten/src/ATen/mps/MPSHooks.mm",
          "aten/src/ATen/native/Pool.h",
          "aten/src/ATen/native/mps/OperationUtils.h",
          "aten/src/ATen/native/mps/kernels/Attention.metal",
          "aten/src/ATen/native/mps/operations/Attention.mm",
          "aten/src/ATen/test/tensor_iterator_test.cpp",
          "buckbuild.bzl",
          "build.bzl",
          "build_variables.bzl",
          "c10/core/StorageImpl.h",
          "c10/core/impl/COW.cpp",
          "c10/core/impl/COW.h",
          "c10/test/core/impl/cow_test.cpp",
          "c10/util/complex_math.h",
          "caffe2/CMakeLists.txt",
          "docs/source/user_guide/torch_compiler/torch.compiler.md",
          "docs/source/user_guide/torch_compiler/torch.compiler_dynamo_overview.md",
          "docs/source/user_guide/torch_compiler/torch.compiler_fake_tensor.md",
          "docs/source/user_guide/torch_compiler/torch.compiler_get_started.md",
          "pt_template_srcs.bzl",
          "setup.py",
          "test/cpp_extensions/libtorch_agn_2_9_extension/csrc/kernel.cpp",
          "test/cpp_extensions/open_registration_extension/torch_openreg/tests/test_testing.py",
          "test/distributed/test_fake_pg.py",
          "test/dynamo/test_aot_autograd_cache.py",
          "test/dynamo/test_dicts.py",
          "test/dynamo/test_functions.py",
          "test/dynamo/test_guard_manager.py",
          "test/dynamo/test_misc.py",
          "test/dynamo/test_repros.py",
          "test/dynamo/test_unspec.py",
          "test/functorch/test_aotdispatch.py",
          "test/inductor/test_autoheuristic.py",
          "test/inductor/test_coordinate_descent_tuner.py",
          "test/inductor/test_flex_attention.py",
          "test/inductor/test_fp8.py",
          "test/inductor/test_remote_cache.py",
          "test/inductor/test_triton_kernels.py",
          "test/inductor/test_triton_wrapper.py",
          "test/inductor/test_utils.py",
          "test/test_accelerator.py",
          "test/test_cuda.py",
          "test/test_dynamic_shapes.py",
          "test/test_fake_tensor.py",
          "test/test_mps.py",
          "test/test_python_dispatch.py",
          "test/test_reductions.py",
          "tools/autograd/gen_trace_type.py",
          "tools/autograd/gen_variable_type.py",
          "torch/_C/_dynamo/guards.pyi",
          "torch/_decomp/decompositions.py",
          "torch/_dynamo/decorators.py",
          "torch/_dynamo/guards.py",
          "torch/_dynamo/utils.py",
          "torch/_dynamo/variables/base.py",
          "torch/_dynamo/variables/builder.py",
          "torch/_dynamo/variables/builtin.py",
          "torch/_dynamo/variables/constant.py",
          "torch/_dynamo/variables/functions.py",
          "torch/_dynamo/variables/nn_module.py",
          "torch/_dynamo/variables/tensor.py",
          "torch/_dynamo/variables/user_defined.py",
          "torch/_export/non_strict_utils.py",
          "torch/_export/serde/schema_check.py",
          "torch/_functorch/_aot_autograd/functional_utils.py",
          "torch/_functorch/_aot_autograd/runtime_wrappers.py",
          "torch/_inductor/autoheuristic/autoheuristic.py",
          "torch/_inductor/autotune_process.py",
          "torch/_inductor/codecache.py",
          "torch/_inductor/codegen/cpp_wrapper_cpu.py",
          "torch/_inductor/codegen/cpu_device_op_overrides.py",
          "torch/_inductor/codegen/simd.py",
          "torch/_inductor/codegen/triton_combo_kernel.py",
          "torch/_inductor/codegen/wrapper.py",
          "torch/_inductor/compile_fx.py",
          "torch/_inductor/config.py",
          "torch/_inductor/fx_passes/post_grad.py",
          "torch/_inductor/fx_utils.py",
          "torch/_inductor/ir.py",
          "torch/_inductor/mock_cache.py",
          "torch/_inductor/remote_cache.py",
          "torch/_inductor/runtime/autotune_cache.py",
          "torch/_inductor/runtime/benchmarking.py",
          "torch/_inductor/runtime/coordinate_descent_tuner.py",
          "torch/_inductor/runtime/debug_utils.py",
          "torch/_inductor/runtime/triton_heuristics.py",
          "torch/_native/README.md",
          "torch/_subclasses/meta_utils.py",
          "torch/csrc/Module.cpp",
          "torch/csrc/distributed/c10d/FakeProcessGroup.hpp",
          "torch/csrc/distributed/c10d/symm_mem/CUDASymmetricMemory.hpp",
          "torch/csrc/distributed/rpc/rref_proto.cpp",
          "torch/csrc/dynamo/guards.cpp",
          "torch/csrc/jit/python/pybind_utils.h",
          "torch/csrc/jit/serialization/pickler.cpp",
          "torch/csrc/stable/tensor_struct.h",
          "torch/csrc/utils/python_numbers.h",
          "torch/csrc/utils/python_strings.h",
          "torch/cuda/graphs.py",
          "torch/distributed/_local_tensor/__init__.py",
          "torch/distributed/tensor/_api.py",
          "torch/nativert/executor/Weights.cpp",
          "torch/nativert/executor/Weights.h",
          "torch/nativert/graph/Graph.cpp",
          "torch/nativert/graph/Serialization.cpp",
          "torch/nested/_internal/nested_tensor.py",
          "torch/nn/functional.py",
          "torch/testing/_internal/common_device_type.py",
          "torch/testing/_internal/common_methods_invocations.py",
          "torch/testing/_internal/common_modules.py",
          "torch/testing/_internal/common_utils.py",
          "torch/testing/_internal/opinfo/definitions/linalg.py"
        ],
        "removed": [
          "test/dynamo_expected_failures/CPython313-test_set-TestFrozenSet.test_constructor_identity",
          "test/dynamo_expected_failures/CPython313-test_set-TestFrozenSet.test_frozen_as_dictkey",
          "test/dynamo_expected_failures/CPython313-test_set-TestFrozenSet.test_intersection",
          "test/dynamo_expected_failures/CPython313-test_set-TestSet.test_constructor_identity",
          "test/dynamo_expected_failures/CPython313-test_set-TestSet.test_copy",
          "test/dynamo_expected_failures/CPython313-test_set-TestSet.test_intersection"
        ],
        "timestamp": "2026-04-29T09:22:57-07:00",
        "tree_id": "62a60761cfea75b576f1fe958506f6ce62eec0c1",
        "url": "https://github.com/pytorch/pytorch/commit/cb0d97e95f00e31f4de9fb617e19ee785da49b4b"
      },
      "installation": {
        "id": 122659619,
        "node_id": "MDIzOkludGVncmF0aW9uSW5zdGFsbGF0aW9uMTIyNjU5NjE5"
      },
      "organization": {
        "avatar_url": "https://avatars.githubusercontent.com/u/21003710?v=4",
        "description": "",
        "events_url": "https://api.github.com/orgs/pytorch/events",
        "hooks_url": "https://api.github.com/orgs/pytorch/hooks",
        "id": 21003710,
        "issues_url": "https://api.github.com/orgs/pytorch/issues",
        "login": "pytorch",
        "members_url": "https://api.github.com/orgs/pytorch/members{/member}",
        "node_id": "MDEyOk9yZ2FuaXphdGlvbjIxMDAzNzEw",
        "public_members_url": "https://api.github.com/orgs/pytorch/public_members{/member}",
        "repos_url": "https://api.github.com/orgs/pytorch/repos",
        "url": "https://api.github.com/orgs/pytorch"
      },
      "pusher": {
        "email": null,
        "name": "pytorch-bot[bot]"
      },
      "ref": "refs/tags/ciflow/riscv64/181785",
      "repository": {
        "allow_forking": true,
        "archive_url": "https://api.github.com/repos/pytorch/pytorch/{archive_format}{/ref}",
        "archived": false,
        "assignees_url": "https://api.github.com/repos/pytorch/pytorch/assignees{/user}",
        "blobs_url": "https://api.github.com/repos/pytorch/pytorch/git/blobs{/sha}",
        "branches_url": "https://api.github.com/repos/pytorch/pytorch/branches{/branch}",
        "clone_url": "https://github.com/pytorch/pytorch.git",
        "collaborators_url": "https://api.github.com/repos/pytorch/pytorch/collaborators{/collaborator}",
        "comments_url": "https://api.github.com/repos/pytorch/pytorch/comments{/number}",
        "commits_url": "https://api.github.com/repos/pytorch/pytorch/commits{/sha}",
        "compare_url": "https://api.github.com/repos/pytorch/pytorch/compare/{base}...{head}",
        "contents_url": "https://api.github.com/repos/pytorch/pytorch/contents/{+path}",
        "contributors_url": "https://api.github.com/repos/pytorch/pytorch/contributors",
        "created_at": 1471066001,
        "custom_properties": {},
        "default_branch": "main",
        "deployments_url": "https://api.github.com/repos/pytorch/pytorch/deployments",
        "description": "Tensors and Dynamic neural networks in Python with strong GPU acceleration",
        "disabled": false,
        "downloads_url": "https://api.github.com/repos/pytorch/pytorch/downloads",
        "events_url": "https://api.github.com/repos/pytorch/pytorch/events",
        "fork": false,
        "forks": 27619,
        "forks_count": 27619,
        "forks_url": "https://api.github.com/repos/pytorch/pytorch/forks",
        "full_name": "pytorch/pytorch",
        "git_commits_url": "https://api.github.com/repos/pytorch/pytorch/git/commits{/sha}",
        "git_refs_url": "https://api.github.com/repos/pytorch/pytorch/git/refs{/sha}",
        "git_tags_url": "https://api.github.com/repos/pytorch/pytorch/git/tags{/sha}",
        "git_url": "git://github.com/pytorch/pytorch.git",
        "has_discussions": false,
        "has_downloads": true,
        "has_issues": true,
        "has_pages": false,
        "has_projects": true,
        "has_pull_requests": true,
        "has_wiki": true,
        "homepage": "https://pytorch.org",
        "hooks_url": "https://api.github.com/repos/pytorch/pytorch/hooks",
        "html_url": "https://github.com/pytorch/pytorch",
        "id": 65600975,
        "is_template": false,
        "issue_comment_url": "https://api.github.com/repos/pytorch/pytorch/issues/comments{/number}",
        "issue_events_url": "https://api.github.com/repos/pytorch/pytorch/issues/events{/number}",
        "issues_url": "https://api.github.com/repos/pytorch/pytorch/issues{/number}",
        "keys_url": "https://api.github.com/repos/pytorch/pytorch/keys{/key_id}",
        "labels_url": "https://api.github.com/repos/pytorch/pytorch/labels{/name}",
        "language": "Python",
        "languages_url": "https://api.github.com/repos/pytorch/pytorch/languages",
        "license": {
          "key": "other",
          "name": "Other",
          "node_id": "MDc6TGljZW5zZTA=",
          "spdx_id": "NOASSERTION",
          "url": null
        },
        "master_branch": "main",
        "merges_url": "https://api.github.com/repos/pytorch/pytorch/merges",
        "milestones_url": "https://api.github.com/repos/pytorch/pytorch/milestones{/number}",
        "mirror_url": null,
        "name": "pytorch",
        "node_id": "MDEwOlJlcG9zaXRvcnk2NTYwMDk3NQ==",
        "notifications_url": "https://api.github.com/repos/pytorch/pytorch/notifications{?since,all,participating}",
        "open_issues": 18538,
        "open_issues_count": 18538,
        "organization": "pytorch",
        "owner": {
          "avatar_url": "https://avatars.githubusercontent.com/u/21003710?v=4",
          "email": null,
          "events_url": "https://api.github.com/users/pytorch/events{/privacy}",
          "followers_url": "https://api.github.com/users/pytorch/followers",
          "following_url": "https://api.github.com/users/pytorch/following{/other_user}",
          "gists_url": "https://api.github.com/users/pytorch/gists{/gist_id}",
          "gravatar_id": "",
          "html_url": "https://github.com/pytorch",
          "id": 21003710,
          "login": "pytorch",
          "name": "pytorch",
          "node_id": "MDEyOk9yZ2FuaXphdGlvbjIxMDAzNzEw",
          "organizations_url": "https://api.github.com/users/pytorch/orgs",
          "received_events_url": "https://api.github.com/users/pytorch/received_events",
          "repos_url": "https://api.github.com/users/pytorch/repos",
          "site_admin": false,
          "starred_url": "https://api.github.com/users/pytorch/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/pytorch/subscriptions",
          "type": "Organization",
          "url": "https://api.github.com/users/pytorch",
          "user_view_type": "public"
        },
        "private": false,
        "pull_request_creation_policy": "all",
        "pulls_url": "https://api.github.com/repos/pytorch/pytorch/pulls{/number}",
        "pushed_at": 1777479794,
        "releases_url": "https://api.github.com/repos/pytorch/pytorch/releases{/id}",
        "size": 1312353,
        "ssh_url": "org-21003710@github.com:pytorch/pytorch.git",
        "stargazers": 99528,
        "stargazers_count": 99528,
        "stargazers_url": "https://api.github.com/repos/pytorch/pytorch/stargazers",
        "statuses_url": "https://api.github.com/repos/pytorch/pytorch/statuses/{sha}",
        "subscribers_url": "https://api.github.com/repos/pytorch/pytorch/subscribers",
        "subscription_url": "https://api.github.com/repos/pytorch/pytorch/subscription",
        "svn_url": "https://github.com/pytorch/pytorch",
        "tags_url": "https://api.github.com/repos/pytorch/pytorch/tags",
        "teams_url": "https://api.github.com/repos/pytorch/pytorch/teams",
        "topics": [
          "autograd",
          "deep-learning",
          "gpu",
          "machine-learning",
          "neural-network",
          "numpy",
          "python",
          "tensor"
        ],
        "trees_url": "https://api.github.com/repos/pytorch/pytorch/git/trees{/sha}",
        "updated_at": "2026-04-29T16:20:41Z",
        "url": "https://api.github.com/repos/pytorch/pytorch",
        "visibility": "public",
        "watchers": 99528,
        "watchers_count": 99528,
        "web_commit_signoff_required": false
      },
      "sender": {
        "avatar_url": "https://avatars.githubusercontent.com/in/40112?v=4",
        "events_url": "https://api.github.com/users/pytorch-bot%5Bbot%5D/events{/privacy}",
        "followers_url": "https://api.github.com/users/pytorch-bot%5Bbot%5D/followers",
        "following_url": "https://api.github.com/users/pytorch-bot%5Bbot%5D/following{/other_user}",
        "gists_url": "https://api.github.com/users/pytorch-bot%5Bbot%5D/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/apps/pytorch-bot",
        "id": 54816060,
        "login": "pytorch-bot[bot]",
        "node_id": "MDM6Qm90NTQ4MTYwNjA=",
        "organizations_url": "https://api.github.com/users/pytorch-bot%5Bbot%5D/orgs",
        "received_events_url": "https://api.github.com/users/pytorch-bot%5Bbot%5D/received_events",
        "repos_url": "https://api.github.com/users/pytorch-bot%5Bbot%5D/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/pytorch-bot%5Bbot%5D/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/pytorch-bot%5Bbot%5D/subscriptions",
        "type": "Bot",
        "url": "https://api.github.com/users/pytorch-bot%5Bbot%5D",
        "user_view_type": "public"
      }
    }
  }
}
EOF