name: manywheel

on:
  workflow_dispatch:
    inputs:
      ref:
        description: The git ref to trigger the workflow on
        required: true
        type: string
      sha:
        description: |
          The git sha to trigger the workflow on; it falls back to the ref
        required: false
        type: string

run-name: manywheel - ${{ inputs.ref }}

permissions:
  contents: read
  packages: read

defaults:
  run:
    shell: bash --noprofile --norc -exo pipefail {0}

jobs:
  docker-builds:
    runs-on: ubuntu-24.04
    timeout-minutes: 360 # 6h
    concurrency:
      group: docker-builds-${{ github.workflow_ref }}-${{ github.workflow_sha }}-${{ inputs.ref }}
      cancel-in-progress: true
    permissions:
      packages: write
    outputs:
      docker-image: ${{ steps.tag.outputs.docker-image }}
    env:
      DOCKER_IMAGE_NAME: manylinux2_39_riscv64-builder:cpu-riscv64
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@af1e73f918a031802d376d3c8bbc3fe56130a9b0 # v4.4.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@96fe6ef7f33517b61c61be40b68a1882f3264fb8 # v4.2.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@bb05f3f5519dd87d3ba754cc423b652a5edd6d2c # v4.2.0

      - name: Setup git user.name and user.email
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"

      - name: Checkout PyTorch Repository at ${{ inputs.ref }}
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          repository: pytorch/pytorch
          ref: ${{ inputs.sha || inputs.ref }}
          fetch-depth: 2147483647 # require the full history
          submodules: recursive

      # FIXME: remove once riseproject-dev/pytorch:manywheel-riscv64 is merged into pytorch/pytorch
      - name: Merge riseproject-dev/pytorch:manywheel-riscv64
        run: |
          git remote add riseproject-dev https://github.com/riseproject-dev/pytorch.git
          git pull --commit --no-ff --no-verify --no-tags --no-recurse-submodules --verbose riseproject-dev manywheel-riscv64

      - name: Compute image tag
        id: tag
        run: |
          echo "docker-image=ghcr.io/riseproject-dev/pytorch/${DOCKER_IMAGE_NAME}-$(git rev-parse HEAD:.ci/docker)" >> "${GITHUB_OUTPUT}"

      - name: Build and push to GitHub Container Registry
        env:
          REMOTE_BUILDKIT: "1"
          CI: "1"
          DOCKER_IMAGE: ${{ steps.tag.outputs.docker-image }}
        run: |
          # Check if image already exists, if it does then skip building it
          if docker manifest inspect "${DOCKER_IMAGE}"; then
            exit 0
          fi

          cd .ci/docker
          ./manywheel/build.sh "${DOCKER_IMAGE_NAME}" -t "${DOCKER_IMAGE}"

          # manywheel/build.sh doesn't push by default
          docker push ${DOCKER_IMAGE}

  linux-riscv64-binary-manywheel:
    name: linux-riscv64-binary-manywheel
    runs-on: ubuntu-24.04-riscv
    timeout-minutes: 1440 # 24h
    concurrency:
      group: linux-riscv64-binary-manywheel-build-${{ github.workflow_ref }}-${{ github.workflow_sha }}-${{ inputs.ref }}
      cancel-in-progress: true
    needs:
      - docker-builds
    container:
      image: ${{ needs.docker-builds.outputs.docker-image }}
    env:
      BUILD_ENVIRONMENT: linux-riscv64-binary-manywheel
      PYTORCH_ROOT: ${{ github.workspace }}/pytorch
      BINARY_ENV_FILE: /tmp/env
      PACKAGE_TYPE: manywheel
      DESIRED_CUDA: cpu
      GPU_ARCH_VERSION: ""
      GPU_ARCH_TYPE: cpu-riscv64
      DOCKER_IMAGE: ${{ needs.docker-builds.outputs.docker-image }}
      SKIP_ALL_TESTS: 1
      # DESIRED_PYTHONS: "3.10 3.11 3.12 3.13 3.14 3.14t 3.15 3.15t"
      DESIRED_PYTHONS: "3.12"
      BUILD_NAME_PREFIX: "manywheel-py"
      BUILD_NAME_SUFFIX: "-cpu-riscv64"

    steps:
      - name: Setup git user.name and user.email
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"

      - name: Checkout PyTorch Repository at ${{ inputs.ref }}
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          repository: pytorch/pytorch
          ref: ${{ inputs.sha || inputs.ref }}
          fetch-depth: 2147483647 # require the full history
          submodules: recursive
          path: pytorch

      - name: Setup git safe.directory
        run: |
          git config --global safe.directory '*'

      # FIXME: remove once riseproject-dev/pytorch:manywheel-riscv64 is merged into pytorch/pytorch
      - name: Merge riseproject-dev/pytorch:manywheel-riscv64
        working-directory: pytorch
        run: |
          git remote add riseproject-dev https://github.com/riseproject-dev/pytorch.git
          git pull --commit --no-ff --no-verify --no-tags --no-recurse-submodules --verbose riseproject-dev manywheel-riscv64

      - name: Set MAX_JOBS=$(nproc)
        run: echo "MAX_JOBS=$(nproc)" >> "${GITHUB_ENV}"

      - name: Populate binary env
        shell: bash
        working-directory: pytorch
        run: |
          export PYTORCH_FINAL_PACKAGE_DIR="${RUNNER_TEMP}/artifacts"
          mkdir -p "${PYTORCH_FINAL_PACKAGE_DIR}"
          echo "PYTORCH_FINAL_PACKAGE_DIR=${PYTORCH_FINAL_PACKAGE_DIR}" >> "${GITHUB_ENV}"
          bash .ci/pytorch/binary_populate_env.sh

      - name: Build all wheels
        id: build
        working-directory: pytorch
        run: |
          # shellcheck disable=SC1091
          source "${BINARY_ENV_FILE}"
          bash .ci/manywheel/build_all.sh

      - name: Store PyTorch Build Artifacts
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        if: steps.build.outcome != 'skipped'
        with:
          name: ${{ env.BUILD_ENVIRONMENT }}
          retention-days: 14
          if-no-files-found: warn
          path: |
            pytorch/dist/
            pytorch/build/custom_test_artifacts
            pytorch/build/lib
            pytorch/build/bin
            pytorch/.additional_ci_files
