name: PyTorch Out-of-Tree CI

run-name: >-
  PyTorch CI -
  ${{
    github.event.client_payload.event_type == 'push' &&
      format('Push {0}',
        github.event.client_payload.payload.ref)
  }}

on:
  repository_dispatch:
    types:
      # - pull_request
      - push

concurrency:
  group: >-
    pytorch-ci-${{ github.event.client_payload.payload.repository.full_name }}-${{ github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      should-run: ${{ steps.setup.outputs.should-run }}
      sha: ${{ steps.setup.outputs.sha }}
    steps:
      - name: Set up variables
        id: setup
        run: |
          set -x # log executed commands
          if ${{ github.event.client_payload.event_type == 'push' && !github.event.client_payload.payload.deleted }}; then
            test "${{ github.event.client_payload.payload.after }}" != "0000000000000000000000000000000000000000" || \
              (echo "github.event.client_payload.payload.after should not be all zeroes"; exit 1)
            echo "sha=${{ github.event.client_payload.payload.after }}" >> $GITHUB_OUTPUT
            if ${{ startsWith(github.event.client_payload.payload.ref, 'refs/tags/trunk/') && github.event.client_payload.payload.base_ref == 'refs/heads/main' }}; then
              # It's a push to refs/heads/main
              echo "should-run=true" >> $GITHUB_OUTPUT
            elif ${{ startsWith(github.event.client_payload.payload.ref, 'refs/tags/ciflow/riscv64/') }}; then
              # It's a `ciflow/riscv64` label
              echo "should-run=true" >> $GITHUB_OUTPUT
            fi
          fi

      - name: Log event in step summary
        if: always()
        run: |
          # Log the github.event for future reference
          cat <<'EOF' >> $GITHUB_STEP_SUMMARY
          ```
          ${{ toJson(github.event) }}
          ```
          EOF

  ci:
    if: ${{ needs.setup.outputs.should-run == 'true' }}
    needs: [setup]
    runs-on: ubuntu-24.04-riscv
    steps:
      - name: Checkout PyTorch at triggered commit
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          repository: pytorch/pytorch
          ref: ${{ needs.setup.outputs.sha }}

      - name: Build and test
        run: |
          # Your build and test commands
          echo "Running tests against PyTorch..."
