name: PyTorch Out-of-Tree Dispatch

on:
  repository_dispatch:
    types:
      # - pull_request
      - push

run-name: Dispatch - ${{ github.event.client_payload.payload.ref }}

permissions:
  actions: write

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Set up variables
        id: setup
        run: |
          set -x # log executed commands
          if ${{ github.event.client_payload.payload.repository.full_name == 'pytorch/pytorch' && github.event.client_payload.event_type == 'push' && !github.event.client_payload.payload.deleted }}; then
            test "${{ github.event.client_payload.payload.after }}" != "0000000000000000000000000000000000000000" || \
              (echo "github.event.client_payload.payload.after should not be all zeroes"; exit 1)
            echo "sha=${{ github.event.client_payload.payload.after }}" >> $GITHUB_OUTPUT
            echo "ref=${{ github.event.client_payload.payload.ref }}" >> $GITHUB_OUTPUT
            if ${{ startsWith(github.event.client_payload.payload.ref, 'refs/tags/trunk/') && github.event.client_payload.payload.base_ref == 'refs/heads/main' }}; then
              # It's a push to refs/heads/main
              echo "should-run=true" >> $GITHUB_OUTPUT
            # elif ${{ startsWith(github.event.client_payload.payload.ref, 'refs/tags/ciflow/trunk/') }}; then
            #   # It's a push to a pull request
            #   echo "should-run=true" >> $GITHUB_OUTPUT
            elif ${{ startsWith(github.event.client_payload.payload.ref, 'refs/tags/ciflow/riscv64/') }}; then
              # It's a `ciflow/riscv64` label
              echo "should-run=true" >> $GITHUB_OUTPUT
            fi
          fi

      - name: Trigger CI workflow
        if: steps.setup.outputs.should-run == 'true'
        env:
          GH_TOKEN: ${{ github.token }}
        run: >-
          gh api
          --method POST
          /repos/${{ github.repository }}/actions/workflows/ci.yml/dispatches
          -f 'ref=${{ github.event.repository.default_branch }}'
          -f 'inputs[ref]=${{ steps.setup.outputs.ref }}'
          -f 'inputs[sha]=${{ steps.setup.outputs.sha }}'

      - name: Log event in step summary
        if: always()
        run: |
          # Log the github.event for future reference
          cat <<'EOF' >> $GITHUB_STEP_SUMMARY
          ```
          ${{ toJson(github.event) }}
          ```
          EOF
